services:
  chuckey-ui:
    image: ghcr.io/rollinglabs/chuckey-ui:latest
    container_name: chuckey-ui
    restart: unless-stopped
    network_mode: host
    cap_add:
      - SYS_ADMIN
    volumes:
      - /chuckey:/chuckey:ro
      - /chuckey/logs:/app/logs
      - /chuckey/data:/app/data
      - /var/lib/chuckey:/var/lib/chuckey
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  unifi-controller:
    image: jacobalberty/unifi:latest
    container_name: unifi-controller
    restart: unless-stopped
    network_mode: host
    volumes:
      - /unifi-controller/data:/unifi/data
      - /unifi-controller/log:/unifi/log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8443'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s